[colors]
primary = {  foreground = "#d3c6aa", background = "#2d353b"}

normal.black   = "#475258"
normal.red     = "#e67e80"
normal.green   = "#a7c080"
normal.yellow  = "#dbbc7f"
normal.blue    = "#7fbbb3"
normal.magenta = "#d699b6"
normal.cyan    = "#83c092"
normal.white   = "#d3c6aa"

bright.black   = "#475258"
bright.red     = "#e67e80"
bright.green   = "#a7c080"
bright.yellow  = "#dbbc7f"
bright.blue    = "#7fbbb3"
bright.magenta = "#d699b6"
bright.cyan    = "#83c092"
bright.white   = "#d3c6aa"
