import = [
    # "~/.config/alacritty/themes/nightfox.toml"
    # "~/.config/alacritty/themes/atom_one_light.toml"
    # "~/.config/alacritty/themes/everforest_dark.toml"
    "~/.config/alacritty/themes/gruvbox_dark.toml"
    # "~/.config/alacritty/themes/github_light.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "/usr/local/bin/tmux"
args = ["-u", "new", "-A", "-s", "worklife"]

[scrolling]
history = 10000

[window]
padding = { x = 5, y = 5 }
decorations = "Full"
dimensions = { columns = 180, lines = 60 }
# startup_mode = "Maximized"

[cursor]
style = { shape = "Block", blinking = "On" }

[font]
size = 16.0
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    # { key = "Left", mods = "Command", chars = "\U1bOH" },
    # { key = "Right", mods = "Command", chars = \x1bOF },
    # { key = "Left", mods = "Alt", chars = "\x1bb" },
    # { key = "Right", mods = "Alt", chars = "\x1bf" }

]
